name: FE pipeline

on:
  workflow_dispatch:
    inputs:
      fe-version:
        type: string
        description: Frontend version which will be deployed to prod
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.fe-version }}

      - name: Verify checkout
        run: git log --oneline -1
