name: Release
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "20"

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{secrets.SECRET_KEY}}

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm clean-install

      - name: Check for new releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_VERSION=$(npx semantic-release --dry-run | grep -oP "(?<=The next release version is )\S*")
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo $NEW_VERSION
        continue-on-error: true

      - run: echo "the version is ${{ env.new_version }}"

      - name: Increment build when no new version is found
        if: ${{ env.new_version == '' }}
        run: |
          CURRENT_BUILD=$(jq '.custom_entries.build_number' package.json)
          echo "Current build number: $current_build"

          NEW_BUILD=$((CURRENT_BUILD + 1))
          echo "New build number: $NEW_BUILD"
          echo "build_number=$NEW_BUILD" >> $GITHUB_ENV

          jq ".custom_entries.build_number = $NEW_BUILD" package.json > package.tmp.json && mv package.tmp.json package.json

      - name: Commit new build
        if: ${{ env.new_version == '' && env.build_number != '' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[skip ci] incremented build number"
          git push

      - name: Process new version
        if: ${{ env.new_version != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Version retrieval succeeded. New version ${{ env.new_version }} will be released."
          npx semantic-release
          jq ".custom_entries.build_number = 1" package.json > package.tmp.json && mv package.tmp.json package.json

      - name: Reset build when new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[skip ci] reset build number"
          git push
